name: Expo Build (CD)

on:
  push:
    branches:
      main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Expo CLI
        uses: expo/setup-expo@v1
        with:
          expo-sdk: ^44.0.0

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: npm install

      - name: Set EXPO_TOKEN
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Replace with your actual token
        run: echo "::add-mask::EXPO_TOKEN"  # Mask the token for security

      - name: Build Expo app
        run: eas build --platform android --non-interactive --no-wait
